print("welcome to the band generator.")
city = input("which city did you grow up in?\n")
print(city)
pet = input("what is the name of your pet\n")
print(pet)
print(" your band name could be " + city + " " + pet)
